import { Inter } from "next/font/google";
import "./globals.css";
import Head from "./components/Head";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Estabrk",
  description: "Generated by Ahmed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
          <Head />
          {children}
          <Footer />
      </body>
    </html>
  );
}
